/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as EkosistemRouteImport } from './routes/ekosistem'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as KeberlanjutanRouteImport } from './routes/keberlanjutan'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as LegalitasRouteImport } from './routes/legalitas'
import { Route as ManajemenRouteImport } from './routes/manajemen'
import { Route as PenawaranRouteImport } from './routes/penawaran'
import { Route as ProdukRouteImport } from './routes/produk'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as ArtikelIndexRouteImport } from './routes/artikel/index'
import { Route as ArtikelSlugRouteImport } from './routes/artikel/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EkosistemRoute = EkosistemRouteImport.update({
  id: '/ekosistem',
  path: '/ekosistem',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const KeberlanjutanRoute = KeberlanjutanRouteImport.update({
  id: '/keberlanjutan',
  path: '/keberlanjutan',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalitasRoute = LegalitasRouteImport.update({
  id: '/legalitas',
  path: '/legalitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ManajemenRoute = ManajemenRouteImport.update({
  id: '/manajemen',
  path: '/manajemen',
  getParentRoute: () => rootRouteImport,
} as any)
const PenawaranRoute = PenawaranRouteImport.update({
  id: '/penawaran',
  path: '/penawaran',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukRoute = ProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ekosistem': typeof EkosistemRoute
  '/faq': typeof FaqRoute
  '/investor': typeof InvestorRoute
  '/keberlanjutan': typeof KeberlanjutanRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/legalitas': typeof LegalitasRoute
  '/manajemen': typeof ManajemenRoute
  '/penawaran': typeof PenawaranRoute
  '/produk': typeof ProdukRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang': typeof TentangRoute
  '/testimoni': typeof TestimoniRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ekosistem': typeof EkosistemRoute
  '/faq': typeof FaqRoute
  '/investor': typeof InvestorRoute
  '/keberlanjutan': typeof KeberlanjutanRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/legalitas': typeof LegalitasRoute
  '/manajemen': typeof ManajemenRoute
  '/penawaran': typeof PenawaranRoute
  '/produk': typeof ProdukRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang': typeof TentangRoute
  '/testimoni': typeof TestimoniRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/artikel': typeof ArtikelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ekosistem': typeof EkosistemRoute
  '/faq': typeof FaqRoute
  '/investor': typeof InvestorRoute
  '/keberlanjutan': typeof KeberlanjutanRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kontak': typeof KontakRoute
  '/legalitas': typeof LegalitasRoute
  '/manajemen': typeof ManajemenRoute
  '/penawaran': typeof PenawaranRoute
  '/produk': typeof ProdukRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang': typeof TentangRoute
  '/testimoni': typeof TestimoniRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ekosistem'
    | '/faq'
    | '/investor'
    | '/keberlanjutan'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/legalitas'
    | '/manajemen'
    | '/penawaran'
    | '/produk'
    | '/syarat-ketentuan'
    | '/tentang'
    | '/testimoni'
    | '/admin/leads'
    | '/artikel/$slug'
    | '/artikel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ekosistem'
    | '/faq'
    | '/investor'
    | '/keberlanjutan'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/legalitas'
    | '/manajemen'
    | '/penawaran'
    | '/produk'
    | '/syarat-ketentuan'
    | '/tentang'
    | '/testimoni'
    | '/admin/leads'
    | '/artikel/$slug'
    | '/artikel'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/ekosistem'
    | '/faq'
    | '/investor'
    | '/keberlanjutan'
    | '/kebijakan-privasi'
    | '/kontak'
    | '/legalitas'
    | '/manajemen'
    | '/penawaran'
    | '/produk'
    | '/syarat-ketentuan'
    | '/tentang'
    | '/testimoni'
    | '/admin/leads'
    | '/artikel/$slug'
    | '/artikel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  EkosistemRoute: typeof EkosistemRoute
  FaqRoute: typeof FaqRoute
  InvestorRoute: typeof InvestorRoute
  KeberlanjutanRoute: typeof KeberlanjutanRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KontakRoute: typeof KontakRoute
  LegalitasRoute: typeof LegalitasRoute
  ManajemenRoute: typeof ManajemenRoute
  PenawaranRoute: typeof PenawaranRoute
  ProdukRoute: typeof ProdukRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TentangRoute: typeof TentangRoute
  TestimoniRoute: typeof TestimoniRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekosistem': {
      id: '/ekosistem'
      path: '/ekosistem'
      fullPath: '/ekosistem'
      preLoaderRoute: typeof EkosistemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keberlanjutan': {
      id: '/keberlanjutan'
      path: '/keberlanjutan'
      fullPath: '/keberlanjutan'
      preLoaderRoute: typeof KeberlanjutanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legalitas': {
      id: '/legalitas'
      path: '/legalitas'
      fullPath: '/legalitas'
      preLoaderRoute: typeof LegalitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manajemen': {
      id: '/manajemen'
      path: '/manajemen'
      fullPath: '/manajemen'
      preLoaderRoute: typeof ManajemenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penawaran': {
      id: '/penawaran'
      path: '/penawaran'
      fullPath: '/penawaran'
      preLoaderRoute: typeof PenawaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk': {
      id: '/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  EkosistemRoute: EkosistemRoute,
  FaqRoute: FaqRoute,
  InvestorRoute: InvestorRoute,
  KeberlanjutanRoute: KeberlanjutanRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KontakRoute: KontakRoute,
  LegalitasRoute: LegalitasRoute,
  ManajemenRoute: ManajemenRoute,
  PenawaranRoute: PenawaranRoute,
  ProdukRoute: ProdukRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TentangRoute: TentangRoute,
  TestimoniRoute: TestimoniRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
